import type { MvpTrialContentPack } from '../../template-engine';

export const mvpTrialContentPackReadyExample: MvpTrialContentPack = {
  packId: 'mvp-trial-content-pack-13a-ready',
  title: 'Phase 13A MVP Trial Content Pack',
  purpose:
    '给创始人 demo 和小范围 MVP 试跑使用的本地试用内容包，不是正式模板库。',
  ordinaryUserDemoOrder: [
    '打开用户 App MVP 首页',
    '浏览三套试用妆容',
    '选择一套进入详情',
    '查看准备页和工具清单',
    '完成分步跟练预览',
    '查看完成页和隐私说明',
  ],
  templateStudioDemoOrder: [
    '展示 photo-to-template operator workflow',
    '展示 draft preview QA',
    '展示 acceptance trial boundary',
    '展示 Founder Demo Review summary',
  ],
  forbiddenClaims: [
    'fully automatic extraction',
    'AI confirmed final look',
    'published template',
    'registry written',
    'production ready',
    'medical diagnosis',
    'exact product shade match',
  ],
  registryChainPausedAfter10U: true,
  trialContentNotOfficialTemplateLibrary: true,
  noRealUserPhotoIncluded: true,
  noRegistryWrite: true,
  noPublish: true,
  templates: [
    {
      templateId: 'mvp-trial-template-beginner-commute',
      title: '新手通勤淡妆',
      englishLabel: 'Beginner Commute Soft Makeup',
      summary:
        '适合第一次跟练的日常淡妆，重点是均匀底妆、自然眉眼和低失误率的气色提升。',
      suitableScenarios: ['上班', '上课', '视频会议', '日常出门'],
      targetUser: '化妆新手或希望快速完成自然妆效的人',
      difficulty: 'easy',
      estimatedMinutes: 12,
      toolsChecklist: ['粉扑或海绵', '眉笔', '眼影刷', '腮红刷', '唇刷可选'],
      productPlaceholders: ['轻薄底妆产品', '自然棕眉笔', '低饱和眼影', '柔和腮红', '日常唇色'],
      sourceLabel: 'local_trial_content',
      notFromAutomaticExtraction: true,
      humanReviewRecommended: true,
      steps: [
        {
          stepId: 'commute-base',
          order: 1,
          region: 'base',
          goal: '让肤色更均匀但保留自然皮肤质感',
          instruction: '少量多次铺开底妆，重点轻拍鼻翼、嘴角和泛红区域。',
          beginnerTip: '先用半泵量，不够再补，避免第一步就变厚。',
          commonMistakes: ['一次取太多', '边缘没有拍开'],
          correctionTips: ['用干净粉扑压一遍边界', '只在暗沉处少量补第二层'],
        },
        {
          stepId: 'commute-brow-eye',
          order: 2,
          region: 'brow_eye',
          goal: '补足眉形和眼神，不做复杂眼妆',
          instruction: '沿眉毛空缺处轻描，再用浅棕色眼影扫眼窝和下眼尾。',
          beginnerTip: '眉头留浅，眉尾再加深。',
          commonMistakes: ['眉头过重', '眼影边界明显'],
          correctionTips: ['用螺旋刷刷淡眉头', '用干净刷晕开眼影边缘'],
        },
        {
          stepId: 'commute-cheek-lip',
          order: 3,
          region: 'cheek_lip',
          goal: '提升气色，保持通勤自然度',
          instruction: '腮红从苹果肌向太阳穴轻扫，唇色薄涂后用指腹压开。',
          beginnerTip: '先轻后重，镜子拿远确认整体气色。',
          commonMistakes: ['腮红范围太低', '唇线过硬'],
          correctionTips: ['用底妆余粉弱化腮红边缘', '用纸巾轻抿降低唇色饱和度'],
        },
      ],
      completionReview: ['肤色均匀', '眉眼自然', '整体不厚重', '近看无明显边界'],
      demoRiskNotes: ['不承诺适合所有肤质', '不做产品色号硬匹配', '仍需人工审核后再扩展'],
    },
    {
      templateId: 'mvp-trial-template-jp-date',
      title: '日系温柔约会妆',
      englishLabel: 'Japanese Soft Date Makeup',
      summary:
        '强调柔和眼影、干净腮红和低攻击性的唇颊协调，适合想要温柔氛围的试用者。',
      suitableScenarios: ['约会', '朋友聚会', '周末拍照', '轻正式场合'],
      targetUser: '有一点化妆基础，想学习柔和氛围感的人',
      difficulty: 'medium',
      estimatedMinutes: 18,
      toolsChecklist: ['眼影刷', '晕染刷', '腮红刷', '睫毛夹', '唇刷可选'],
      productPlaceholders: ['柔雾底妆', '粉棕眼影', '自然睫毛产品', '粉调腮红', '柔和唇色'],
      sourceLabel: 'local_trial_content',
      notFromAutomaticExtraction: true,
      humanReviewRecommended: true,
      steps: [
        {
          stepId: 'jp-soft-base',
          order: 1,
          region: 'base',
          goal: '保持干净底妆和柔和光泽',
          instruction: '先均匀肤色，再在面中少量提亮，避开过厚遮盖。',
          beginnerTip: '提亮区域只放在眼下三角和鼻梁中段。',
          commonMistakes: ['全脸过亮', '遮瑕边界明显'],
          correctionTips: ['用粉扑压开提亮边缘', '用少量散粉固定易脱妆处'],
        },
        {
          stepId: 'jp-soft-eyes',
          order: 2,
          region: 'eyes',
          goal: '用粉棕层次做温柔眼神',
          instruction: '浅色打底，中间色叠在双眼皮褶和下眼尾，深色只贴近睫毛根部。',
          beginnerTip: '每层范围都比上一层小一点。',
          commonMistakes: ['深色范围太大', '下眼影太脏'],
          correctionTips: ['用浅色刷回边缘', '用棉签清理下眼影过界处'],
        },
        {
          stepId: 'jp-soft-cheek-lip',
          order: 3,
          region: 'cheek_lip',
          goal: '让腮红和唇色互相呼应',
          instruction: '腮红横向轻扫在面中偏高处，唇色薄涂两层增加柔和饱和度。',
          beginnerTip: '腮红和唇色选相近色系即可，不追求完全一致。',
          commonMistakes: ['腮红太靠鼻翼', '唇色太厚'],
          correctionTips: ['用底妆余量压淡鼻侧', '用纸巾轻压唇心后补透明润泽感'],
        },
      ],
      completionReview: ['眼妆边界柔和', '腮红位置偏高', '唇颊色调协调', '没有硬朗线条'],
      demoRiskNotes: ['不声称自动识别风格最终正确', '不替代人工妆容判断', '不写入正式模板库'],
    },
    {
      templateId: 'mvp-trial-template-kr-low-saturation',
      title: '韩系清透低饱和妆',
      englishLabel: 'Korean Clear Low-Saturation Makeup',
      summary:
        '适合演示清透底妆、低饱和眼颊和干净唇妆的跟练路径，突出轻薄和层次控制。',
      suitableScenarios: ['日常拍照', '通勤升级', '约会', '轻社交场合'],
      targetUser: '希望妆面更清透、颜色更克制的人',
      difficulty: 'medium',
      estimatedMinutes: 16,
      toolsChecklist: ['海绵粉扑', '小号眼影刷', '腮红刷', '睫毛夹', '唇刷可选'],
      productPlaceholders: ['清透底妆', '灰棕眼影', '低饱和腮红', '自然睫毛产品', '水润唇色'],
      sourceLabel: 'demo_fixture',
      notFromAutomaticExtraction: true,
      humanReviewRecommended: true,
      steps: [
        {
          stepId: 'kr-clear-base',
          order: 1,
          region: 'base',
          goal: '做出轻薄、干净、不过度遮盖的底妆',
          instruction: '从面中向外轻拍底妆，瑕疵处点压，不在全脸反复叠加。',
          beginnerTip: '清透感来自少量和边界干净，不是全脸发亮。',
          commonMistakes: ['底妆叠太厚', '面部边缘有色差'],
          correctionTips: ['用干净海绵吸走多余底妆', '沿下颌线轻拍过渡'],
        },
        {
          stepId: 'kr-muted-eye-cheek',
          order: 2,
          region: 'eye_cheek',
          goal: '低饱和颜色增加轮廓，不抢整体清透感',
          instruction: '灰棕色轻扫眼窝，腮红从颧骨外侧向内薄扫。',
          beginnerTip: '颜色看不明显也没关系，重点是整体干净。',
          commonMistakes: ['眼影颜色过暖', '腮红太红'],
          correctionTips: ['用肤色粉压淡眼影', '用散粉弱化腮红饱和度'],
        },
        {
          stepId: 'kr-clean-lip',
          order: 3,
          region: 'lip',
          goal: '保留唇部清透感，避免厚重边界',
          instruction: '润唇后薄涂唇色，唇峰和嘴角用指腹轻轻模糊。',
          beginnerTip: '不要勾勒明显唇线，整体会更轻盈。',
          commonMistakes: ['唇色过厚', '嘴角堆积'],
          correctionTips: ['纸巾轻抿后补唇中', '用棉签清理嘴角'],
        },
      ],
      completionReview: ['底妆轻薄', '颜色低饱和', '唇线柔和', '整体清透不过度修饰'],
      demoRiskNotes: ['不收集照片', '不做自动发布', '不生成正式用户 App 模板包'],
    },
  ],
};

export const mvpTrialContentPackSingleTemplateWarningExample: MvpTrialContentPack = {
  ...mvpTrialContentPackReadyExample,
  packId: 'mvp-trial-content-pack-13a-single-template-warning',
  templates: [mvpTrialContentPackReadyExample.templates[0]],
};

export const mvpTrialContentPackBlockedExample: MvpTrialContentPack = {
  ...mvpTrialContentPackReadyExample,
  packId: 'mvp-trial-content-pack-13a-blocked',
  noRegistryWrite: false as true,
};
