import type { UserAppTemplatePackage } from '../schema/user-app-template-contract.schema';

export const userAppTemplatePackageExample: UserAppTemplatePackage = {
  schemaVersion: 'user-app-template-contract-v0.1',
  packageId: 'user-app-template-package-example-v0',
  packageName: 'Example User App Template Package',
  packageVersion: '0.1.0',
  compatibilityTarget: 'web-app-v0',
  createdAt: '2026-06-01T00:00:00.000Z',
  sourcePublishPackageId: 'template-publish-package-example-v0',
  sourcePublishPackageVersion: '0.1.0',
  localOnly: true,
  onlinePublished: false,
  templates: [
    {
      appTemplateId: 'user-app-template-soft-rose-example',
      sourceLibraryEntryId: 'template-library-entry-soft-rose-example',
      sourceTemplateId: 'template-soft-rose-example',
      templateVersion: '0.1.0',
      title: '柔玫瑰日常妆',
      subtitle: '轻柔眉形 / 玫瑰腮红 / 柔雾唇色，适合通勤和日常练习',
      styleTags: ['日常', '自然', '玫瑰色', '新手友好'],
      makeupCategory: 'natural',
      difficulty: 'easy',
      estimatedDurationMinutes: 8,
      suitableOccasions: ['通勤', '日常出门', '朋友小聚'],
      suitableFaceFeatures: ['自然眉形', '中性肤色参考'],
      requiredTools: [
        {
          toolId: 'tool-brush',
          displayName: '小号晕染刷',
          toolType: '刷具',
          required: true,
          usageNotes: ['用于眉毛、眼影和腮红边缘的轻柔晕染，少量多次上色。'],
        },
        {
          toolId: 'tool-finger',
          displayName: '指腹',
          toolType: '手指',
          required: true,
          usageNotes: ['用于轻拍唇色，让边缘自然过渡。'],
        },
      ],
      optionalTools: [],
      productSuggestions: [
        {
          productId: 'product-rose-lip-color',
          displayName: '玫瑰豆沙唇色',
          productCategory: '唇部产品',
          colorHint: '玫瑰豆沙',
          finish: '缎光',
          required: true,
          usageNotes: ['先点在唇中央，再向边缘轻拍，不需要画出明显唇线。'],
        },
        {
          productId: 'product-soft-blush',
          displayName: '柔玫瑰腮红',
          productCategory: '腮红',
          colorHint: '柔玫瑰',
          finish: '缎光',
          required: true,
          usageNotes: ['从苹果肌外侧向太阳穴方向轻扫，边缘保持柔和。'],
        },
        {
          productId: 'product-brow-powder',
          displayName: '灰棕眉粉',
          productCategory: '眉部产品',
          colorHint: '灰棕',
          finish: '柔雾',
          required: true,
          usageNotes: ['只补空缺处，眉头保持轻。'],
        },
        {
          productId: 'product-taupe-eyeshadow',
          displayName: '浅灰棕眼影',
          productCategory: '眼影',
          colorHint: '浅灰棕',
          finish: '柔雾',
          required: true,
          usageNotes: ['铺在活动眼皮内，靠近眼窝边缘时用余粉晕开。'],
        },
      ],
      steps: [
        {
          stepId: 'app-step-brows-example',
          order: 1,
          title: '轻补眉毛空缺',
          instructionText: '用小号刷蘸少量灰棕色，从眉腰到眉尾轻扫，只补明显空缺。眉头用余粉带过，保持毛流感。',
          region: 'brows',
          technique: '顺着眉毛方向轻扫',
          targetEffect: '补齐空缺、保持眉头柔和',
          colorHint: '灰棕',
          intensity: 'low',
          toolIds: ['tool-brush'],
          productIds: ['product-brow-powder'],
          estimatedSeconds: 60,
          commonMistakes: ['眉头一次画太重，会显得生硬。', '眉尾下垂会让整体妆感没精神。'],
          correctionTips: ['用干净刷子把眉头向上梳开。', '眉尾颜色过深时，用刷子余粉向外轻扫淡化。'],
          visualReference: {
            referenceId: 'evidence:brows-example',
            referenceKind: 'evidence-reference',
            description: '已审核的眉毛区域参考，不包含照片数据。',
          },
          evidenceReferences: ['evidence:brows-example'],
          warnings: [],
        },
        {
          stepId: 'app-step-eyeshadow-example',
          order: 2,
          title: '浅灰棕眼影打底',
          instructionText: '从睫毛根部上方开始，把浅灰棕色铺在活动眼皮内。靠近眼窝边缘时用刷上余粉左右晕开，不要超过眼窝太高。',
          region: 'eyeshadow',
          technique: '小范围来回晕染',
          targetEffect: '让眼部轮廓更柔和',
          colorHint: '浅灰棕',
          intensity: 'low',
          toolIds: ['tool-brush'],
          productIds: ['product-taupe-eyeshadow'],
          estimatedSeconds: 80,
          commonMistakes: ['颜色晕到眉骨太高，眼妆会显脏。', '两侧上边缘高度不一致。'],
          correctionTips: ['用干净刷子沿上边缘轻扫 2-3 次。', '闭眼看不到边界时，可以睁眼检查最高点。'],
          visualReference: {
            referenceId: 'evidence:eyeshadow-example',
            referenceKind: 'evidence-reference',
            description: '已审核的眼影区域参考，不包含照片数据。',
          },
          evidenceReferences: ['evidence:eyeshadow-example'],
          warnings: [],
        },
        {
          stepId: 'app-step-blush-example',
          order: 3,
          title: '腮红向外晕开',
          instructionText: '微笑找到脸颊最高处外侧，从那里向太阳穴方向轻扫柔玫瑰腮红。第一遍颜色要淡，确认两边位置对称后再叠加。',
          region: 'blush',
          technique: '从内向外轻扫并晕开边缘',
          targetEffect: '提气色、让脸颊更柔和',
          colorHint: '柔玫瑰',
          intensity: 'medium',
          toolIds: ['tool-brush'],
          productIds: ['product-soft-blush'],
          estimatedSeconds: 70,
          commonMistakes: ['腮红位置太低会显疲惫。', '边缘像色块，没有晕开。'],
          correctionTips: ['用干净刷子扫开下边缘。', '如果颜色重了，用底妆余粉轻压边缘。'],
          visualReference: {
            referenceId: 'evidence:blush-example',
            referenceKind: 'evidence-reference',
            description: '已审核的腮红区域参考，不包含照片数据。',
          },
          evidenceReferences: ['evidence:blush-example'],
          warnings: [],
        },
        {
          stepId: 'app-step-lips-example',
          order: 4,
          title: '轻拍玫瑰唇色',
          instructionText: '把玫瑰豆沙色点在上下唇中央，用指腹向唇边轻拍。边缘保留一点柔雾感，不需要画出清晰唇线。',
          region: 'lips',
          technique: '中央点涂后向外轻拍',
          targetEffect: '自然提气色、边缘柔和',
          colorHint: '玫瑰豆沙',
          intensity: 'medium',
          toolIds: ['tool-finger'],
          productIds: ['product-rose-lip-color'],
          estimatedSeconds: 55,
          commonMistakes: ['涂到唇线外会显得不整洁。', '唇中央颜色太薄，整体气色不明显。'],
          correctionTips: ['用指腹轻拍唇边，把多余颜色带回唇内。', '只在唇中央补一点颜色，再向外拍开。'],
          visualReference: {
            referenceId: 'evidence:lips-example',
            referenceKind: 'evidence-reference',
            description: '已审核的唇部区域参考，不包含照片数据。',
          },
          evidenceReferences: ['evidence:lips-example'],
          warnings: [],
        },
      ],
      regionInstructions: [
        {
          regionId: 'app-region-brows',
          regionType: 'brows',
          displayName: '眉毛',
          normalizedRegionReference: 'normalized-region:brows',
          applicationAreaDescription: '只补眉毛空缺，眉头保持低强度。',
          intensityRange: { min: 0.1, max: 0.45, recommended: 0.25 },
          blendDirection: '顺着自然眉毛方向',
          edgeSoftness: 'crisp',
          symmetryHint: '定妆前比较两边眉峰和眉尾高度。',
          userGuidanceText: '用轻短笔触补空缺，避免把眉头画成色块。',
        },
        {
          regionId: 'app-region-eyeshadow',
          regionType: 'eyeshadow',
          displayName: '眼影',
          normalizedRegionReference: 'normalized-region:eyeshadow',
          applicationAreaDescription: '活动眼皮和眼窝过渡区。',
          intensityRange: { min: 0.15, max: 0.5, recommended: 0.3 },
          blendDirection: '沿眼窝向外轻扫',
          edgeSoftness: 'soft',
          symmetryHint: '两边眼影上边缘保持同一高度。',
          userGuidanceText: '先把边缘晕开，再决定是否叠加颜色。',
        },
        {
          regionId: 'app-region-blush',
          regionType: 'blush',
          displayName: '腮红',
          normalizedRegionReference: 'normalized-region:blush',
          applicationAreaDescription: '脸颊外侧向上向外晕染。',
          intensityRange: { min: 0.3, max: 0.8, recommended: 0.55 },
          blendDirection: '向外并微微向上',
          edgeSoftness: 'soft',
          symmetryHint: '两边腮红最高点保持接近。',
          userGuidanceText: '腮红要像气色透出来，不要像盖章一样有硬边。',
        },
        {
          regionId: 'app-region-lips',
          regionType: 'lips',
          displayName: '唇部',
          normalizedRegionReference: 'normalized-region:lips',
          applicationAreaDescription: '自然唇形内侧，边缘轻柔过渡。',
          intensityRange: { min: 0.35, max: 0.75, recommended: 0.55 },
          blendDirection: '从唇中央向外',
          edgeSoftness: 'soft',
          symmetryHint: '检查上下唇厚度和左右唇峰是否平衡。',
          userGuidanceText: '少量多次轻拍，唇边保持柔和。',
        },
      ],
      safetyNotes: ['不熟悉的产品先做局部试用。', '如出现刺痛或不适，请停止使用。'],
      appDisplayHints: {
        heroLabel: '柔玫瑰日常妆',
        cardSubtitle: '通勤友好的玫瑰色练习妆',
        colorChips: ['柔玫瑰', '浅灰棕'],
        cautionBadges: [],
        sortPriority: 85,
      },
      lineage: {
        sourcePublishPackageId: 'template-publish-package-example-v0',
        sourceLibraryEntryId: 'template-library-entry-soft-rose-example',
        sourceTemplateId: 'template-soft-rose-example',
        sourceTemplateVersion: '0.1.0',
        sourceProductionBatchId: 'production-batch-example-v0',
        sourceProductionTaskId: 'production-task-example-v0',
        sourceImageId: 'source-image-example-v0',
        evidenceReferences: [
          'evidence:brows-example',
          'evidence:eyeshadow-example',
          'evidence:blush-example',
          'evidence:lips-example',
        ],
        localOnly: true,
        onlinePublished: false,
      },
      compatibility: {
        target: 'web-app-v0',
        schemaVersion: 'user-app-template-contract-v0.1',
        compatible: true,
        warnings: [],
        blockingIssues: [],
      },
      metadata: {
        sourcePackageId: 'template-publish-package-example-v0',
        sourceLibraryEntryId: 'template-library-entry-soft-rose-example',
        sourcePackageVersion: '0.1.0',
        evidenceReady: true,
        qualityScore: 0.85,
        localOnly: true,
        onlinePublished: false,
        notes: ['example package contains references only, not image bytes'],
      },
      createdAt: '2026-06-01T00:00:00.000Z',
    },
  ],
  compatibility: {
    target: 'web-app-v0',
    schemaVersion: 'user-app-template-contract-v0.1',
    compatible: true,
    warnings: [],
    blockingIssues: [],
  },
  validation: {
    valid: true,
    warnings: [],
    blockingIssues: [],
    readiness: {
      ready: true,
      totalTemplates: 1,
      readyTemplates: 1,
      blockedTemplates: 0,
      warningCount: 0,
      blockingIssueCount: 0,
    },
  },
  summary: {
    totalTemplates: 1,
    totalSteps: 4,
    totalRegionInstructions: 4,
    difficultyCounts: { easy: 1, medium: 0, advanced: 0 },
    styleTags: ['日常', '自然', '玫瑰色', '新手友好'],
    estimatedDurationMinutes: { min: 8, max: 8, average: 8 },
  },
  exportNotes: [
    'example only',
    'no object URLs',
    'no local absolute paths',
    'no large image bytes',
  ],
};
