import type { UserAppTemplatePackage } from '../schema/user-app-template-contract.schema';

export const userAppTemplatePackageExample: UserAppTemplatePackage = {
  schemaVersion: 'user-app-template-contract-v0.1',
  packageId: 'user-app-template-package-example-v0',
  packageName: 'Example User App Template Package',
  packageVersion: '0.1.0',
  compatibilityTarget: 'web-app-v0',
  createdAt: '2026-06-01T00:00:00.000Z',
  sourcePublishPackageId: 'template-publish-package-example-v0',
  sourcePublishPackageVersion: '0.1.0',
  localOnly: true,
  onlinePublished: false,
  templates: [
    {
      appTemplateId: 'user-app-template-soft-rose-example',
      sourceLibraryEntryId: 'template-library-entry-soft-rose-example',
      sourceTemplateId: 'template-soft-rose-example',
      templateVersion: '0.1.0',
      title: 'Soft Rose Daily Look',
      subtitle: 'soft blush / rose lip / gentle eyeshadow',
      styleTags: ['daily', 'natural', 'rose'],
      makeupCategory: 'natural',
      difficulty: 'easy',
      estimatedDurationMinutes: 8,
      suitableOccasions: ['daily', 'work', 'casual'],
      suitableFaceFeatures: ['oval', 'neutral skin tone'],
      requiredTools: [
        {
          toolId: 'tool-brush',
          displayName: 'Brush',
          toolType: 'brush',
          required: true,
          usageNotes: ['Use a small brush for blush and eyeshadow blending.'],
        },
        {
          toolId: 'tool-finger',
          displayName: 'Finger',
          toolType: 'finger',
          required: true,
          usageNotes: ['Tap lip color softly into the center.'],
        },
      ],
      optionalTools: [],
      productSuggestions: [
        {
          productId: 'product-rose-lip-color',
          displayName: 'Rose lip color',
          productCategory: 'lip color',
          colorHint: 'rose',
          finish: 'satin',
          required: true,
          usageNotes: ['Keep the edge soft for a daily look.'],
        },
        {
          productId: 'product-soft-blush',
          displayName: 'Soft blush',
          productCategory: 'blush',
          colorHint: 'rose',
          finish: 'satin',
          required: true,
          usageNotes: ['Blend upward from the cheek center.'],
        },
      ],
      steps: [
        {
          stepId: 'app-step-brows-example',
          order: 1,
          title: 'Brows define',
          instructionText: 'Lightly define sparse brow areas and keep the front soft.',
          region: 'brows',
          technique: 'define',
          targetEffect: 'balance',
          colorHint: 'taupe',
          intensity: 'low',
          toolIds: ['tool-brush'],
          productIds: ['product-brow-powder'],
          estimatedSeconds: 60,
          commonMistakes: ['Drawing a harsh brow front.'],
          correctionTips: ['Brush through the brow before adding more color.'],
          visualReference: {
            referenceId: 'evidence:brows-example',
            referenceKind: 'evidence-reference',
            description: 'Reviewed brow placement reference.',
          },
          evidenceReferences: ['evidence:brows-example'],
          warnings: [],
        },
        {
          stepId: 'app-step-eyeshadow-example',
          order: 2,
          title: 'Eyeshadow blend',
          instructionText: 'Blend a muted taupe shade over the mobile lid.',
          region: 'eyeshadow',
          technique: 'blend',
          targetEffect: 'soften',
          colorHint: 'taupe',
          intensity: 'low',
          toolIds: ['tool-brush'],
          productIds: ['product-taupe-eyeshadow'],
          estimatedSeconds: 80,
          commonMistakes: ['Extending color too far above the crease.'],
          correctionTips: ['Use a clean brush to soften the upper edge.'],
          visualReference: {
            referenceId: 'evidence:eyeshadow-example',
            referenceKind: 'evidence-reference',
            description: 'Reviewed eyeshadow region reference.',
          },
          evidenceReferences: ['evidence:eyeshadow-example'],
          warnings: [],
        },
        {
          stepId: 'app-step-blush-example',
          order: 3,
          title: 'Blush blend',
          instructionText: 'Blend soft rose blush from the cheek center outward.',
          region: 'blush',
          technique: 'blend',
          targetEffect: 'lift, soften',
          colorHint: 'rose',
          intensity: 'medium',
          toolIds: ['tool-brush'],
          productIds: ['product-soft-blush'],
          estimatedSeconds: 70,
          commonMistakes: ['Placing blush too low on the cheek.'],
          correctionTips: ['Diffuse the lower edge before increasing color.'],
          visualReference: {
            referenceId: 'evidence:blush-example',
            referenceKind: 'evidence-reference',
            description: 'Reviewed blush mask reference.',
          },
          evidenceReferences: ['evidence:blush-example'],
          warnings: [],
        },
        {
          stepId: 'app-step-lips-example',
          order: 4,
          title: 'Lips fill',
          instructionText: 'Tap rose color inside the lip shape and soften the edge.',
          region: 'lips',
          technique: 'fill',
          targetEffect: 'soften',
          colorHint: 'rose',
          intensity: 'medium',
          toolIds: ['tool-finger'],
          productIds: ['product-rose-lip-color'],
          estimatedSeconds: 55,
          commonMistakes: ['Overdrawing the outer lip edge.'],
          correctionTips: ['Blur the boundary with fingertip pressure.'],
          visualReference: {
            referenceId: 'evidence:lips-example',
            referenceKind: 'evidence-reference',
            description: 'Reviewed lip region reference.',
          },
          evidenceReferences: ['evidence:lips-example'],
          warnings: [],
        },
      ],
      regionInstructions: [
        {
          regionId: 'app-region-brows',
          regionType: 'brows',
          displayName: 'Brows',
          normalizedRegionReference: 'normalized-region:brows',
          applicationAreaDescription: 'Sparse brow areas only; keep front low intensity.',
          intensityRange: { min: 0.1, max: 0.45, recommended: 0.25 },
          blendDirection: 'follow natural hair direction',
          edgeSoftness: 'crisp',
          symmetryHint: 'Compare brow height before setting.',
          userGuidanceText: 'Use light strokes and avoid a blocky brow front.',
        },
        {
          regionId: 'app-region-eyeshadow',
          regionType: 'eyeshadow',
          displayName: 'Eyeshadow',
          normalizedRegionReference: 'normalized-region:eyeshadow',
          applicationAreaDescription: 'Mobile lid and soft crease transition.',
          intensityRange: { min: 0.15, max: 0.5, recommended: 0.3 },
          blendDirection: 'outward along the crease',
          edgeSoftness: 'soft',
          symmetryHint: 'Keep both upper edges at the same height.',
          userGuidanceText: 'Blend the shadow softly before adding more color.',
        },
        {
          regionId: 'app-region-blush',
          regionType: 'blush',
          displayName: 'Blush',
          normalizedRegionReference: 'normalized-region:blush',
          applicationAreaDescription: 'Cheek center diffused upward and outward.',
          intensityRange: { min: 0.3, max: 0.8, recommended: 0.55 },
          blendDirection: 'outward and upward',
          edgeSoftness: 'soft',
          symmetryHint: 'Match cheek height on both sides.',
          userGuidanceText: 'Keep the blush diffused, not stamped.',
        },
        {
          regionId: 'app-region-lips',
          regionType: 'lips',
          displayName: 'Lips',
          normalizedRegionReference: 'normalized-region:lips',
          applicationAreaDescription: 'Inside natural lip shape with softened edge.',
          intensityRange: { min: 0.35, max: 0.75, recommended: 0.55 },
          blendDirection: 'center outward',
          edgeSoftness: 'soft',
          symmetryHint: 'Check upper and lower lip balance.',
          userGuidanceText: 'Tap color gradually and keep the border soft.',
        },
      ],
      safetyNotes: ['Patch test unfamiliar products.', 'Stop if irritation occurs.'],
      appDisplayHints: {
        heroLabel: 'Soft Rose Daily Look',
        cardSubtitle: 'daily rose look',
        colorChips: ['rose', 'taupe'],
        cautionBadges: [],
        sortPriority: 85,
      },
      lineage: {
        sourcePublishPackageId: 'template-publish-package-example-v0',
        sourceLibraryEntryId: 'template-library-entry-soft-rose-example',
        sourceTemplateId: 'template-soft-rose-example',
        sourceTemplateVersion: '0.1.0',
        sourceProductionBatchId: 'production-batch-example-v0',
        sourceProductionTaskId: 'production-task-example-v0',
        sourceImageId: 'source-image-example-v0',
        evidenceReferences: [
          'evidence:brows-example',
          'evidence:eyeshadow-example',
          'evidence:blush-example',
          'evidence:lips-example',
        ],
        localOnly: true,
        onlinePublished: false,
      },
      compatibility: {
        target: 'web-app-v0',
        schemaVersion: 'user-app-template-contract-v0.1',
        compatible: true,
        warnings: [],
        blockingIssues: [],
      },
      metadata: {
        sourcePackageId: 'template-publish-package-example-v0',
        sourceLibraryEntryId: 'template-library-entry-soft-rose-example',
        sourcePackageVersion: '0.1.0',
        evidenceReady: true,
        qualityScore: 0.85,
        localOnly: true,
        onlinePublished: false,
        notes: ['example package contains references only, not image bytes'],
      },
      createdAt: '2026-06-01T00:00:00.000Z',
    },
  ],
  compatibility: {
    target: 'web-app-v0',
    schemaVersion: 'user-app-template-contract-v0.1',
    compatible: true,
    warnings: [],
    blockingIssues: [],
  },
  validation: {
    valid: true,
    warnings: [],
    blockingIssues: [],
    readiness: {
      ready: true,
      totalTemplates: 1,
      readyTemplates: 1,
      blockedTemplates: 0,
      warningCount: 0,
      blockingIssueCount: 0,
    },
  },
  summary: {
    totalTemplates: 1,
    totalSteps: 4,
    totalRegionInstructions: 4,
    difficultyCounts: { easy: 1, medium: 0, advanced: 0 },
    styleTags: ['daily', 'natural', 'rose'],
    estimatedDurationMinutes: { min: 8, max: 8, average: 8 },
  },
  exportNotes: [
    'example only',
    'no object URLs',
    'no local absolute paths',
    'no large image bytes',
  ],
};

