import type { MakeupLook } from '../schema/makeup.schema';

export const koreanGlassSkin: MakeupLook = {
  id: 'look-korean-glass-skin-v01',
  name: 'Korean Glass Skin',
  goals: ['glass_skin', 'brighten_skin', 'natural_glow', 'enlarge_eye'],
  metadata: {
    style: 'k-beauty',
    version: '0.1',
    author: 'Makeup Engine',
    notes: 'A translucent complexion-focused look with soft eyes and hydrated lips.',
  },
  steps: [
    {
      id: 'glass-01-hydrate',
      region: 'face',
      action: 'prep',
      tool: 'finger',
      intensity: 'low',
      description: 'Press hydrating prep into the face until the surface looks plump.',
      product: {
        category: 'hydrating primer',
        finish: 'dewy',
      },
      placement: {
        area: 'entire face',
        coverage: 'full',
      },
      technique: {
        blendMode: 'soft',
        strokeDirection: 'center_out',
        layerOrder: 'base',
        repeat: 2,
      },
      durationMs: 2600,
    },
    {
      id: 'glass-02-sheer-cushion',
      region: 'face',
      action: 'tap',
      tool: 'sponge',
      intensity: 'low',
      description: 'Tap a sheer cushion base in thin layers to keep the skin translucent.',
      dependency: 'glass-01-hydrate',
      product: {
        category: 'cushion foundation',
        shade: 'skin match',
        finish: 'glow',
      },
      placement: {
        area: 'center face and cheek plane',
        coverage: 'medium',
      },
      technique: {
        blendMode: 'diffused',
        strokeDirection: 'center_out',
        layerOrder: 'base',
        repeat: 2,
      },
      durationMs: 2800,
    },
    {
      id: 'glass-03-brighten',
      region: 'face',
      action: 'brighten',
      tool: 'finger',
      intensity: 'medium',
      description: 'Brighten under the eyes and around the nose with a small amount of product.',
      dependency: 'glass-02-sheer-cushion',
      product: {
        category: 'brightening concealer',
        shade: 'half shade lighter',
        finish: 'radiant',
      },
      placement: {
        area: 'under eyes and nose wings',
        coverage: 'small',
      },
      technique: {
        blendMode: 'gradient',
        strokeDirection: 'outward',
        layerOrder: 'base',
        repeat: 1,
      },
      durationMs: 2200,
    },
    {
      id: 'glass-04-straight-brow',
      region: 'eyebrow',
      action: 'define',
      tool: 'brush',
      intensity: 'low',
      description: 'Create a soft straight brow with feathered front hairs.',
      dependency: 'glass-03-brighten',
      product: {
        category: 'brow powder',
        shade: 'ash brown',
        finish: 'soft matte',
      },
      placement: {
        area: 'brow base and tail',
        coverage: 'small',
      },
      technique: {
        blendMode: 'precise',
        strokeDirection: 'follow_growth',
        layerOrder: 'definition',
        repeat: 1,
      },
      durationMs: 1800,
    },
    {
      id: 'glass-05-aegyo-eye',
      region: 'eye',
      action: 'brighten',
      tool: 'brush',
      intensity: 'low',
      description: 'Add a subtle brightening shade to the lower eye area for a fresh look.',
      dependency: 'glass-04-straight-brow',
      product: {
        category: 'brightening shadow',
        shade: 'champagne beige',
        finish: 'pearl',
      },
      placement: {
        area: 'lower inner eye',
        anchor: 'tear trough highlight zone',
        coverage: 'small',
      },
      technique: {
        blendMode: 'soft',
        strokeDirection: 'outward',
        layerOrder: 'color',
        repeat: 1,
      },
      durationMs: 1800,
    },
    {
      id: 'glass-06-gradient-lip',
      region: 'lip',
      action: 'blend',
      tool: 'finger',
      intensity: 'medium',
      description: 'Blend tint from the lip center outward for a soft gradient finish.',
      dependency: 'glass-05-aegyo-eye',
      product: {
        category: 'watery lip tint',
        shade: 'clear coral',
        finish: 'gloss',
      },
      placement: {
        area: 'inner lips',
        coverage: 'medium',
      },
      technique: {
        blendMode: 'gradient',
        strokeDirection: 'lip_center_out',
        layerOrder: 'finish',
        repeat: 2,
      },
      durationMs: 2200,
    },
  ],
};
