import type { MakeupLook } from '../schema/makeup.schema';

export const naturalDaily: MakeupLook = {
  id: 'look-natural-daily-v01',
  name: 'Natural Daily',
  goals: ['brighten_skin', 'natural_glow', 'enlarge_eye'],
  metadata: {
    style: 'natural',
    version: '0.1',
    author: 'Makeup Engine',
    notes: 'A soft everyday look that keeps texture visible and gently opens the eye.',
  },
  steps: [
    {
      id: 'natural-01-skin-prep',
      region: 'face',
      action: 'prep',
      tool: 'finger',
      intensity: 'low',
      description: 'Warm a thin hydrating layer across the face to even out dry patches.',
      product: {
        category: 'skin prep',
        finish: 'hydrated',
      },
      placement: {
        area: 'entire face',
        coverage: 'full',
      },
      technique: {
        blendMode: 'soft',
        strokeDirection: 'center_out',
        layerOrder: 'base',
        repeat: 1,
      },
      durationMs: 2200,
    },
    {
      id: 'natural-02-even-base',
      region: 'face',
      action: 'tap',
      tool: 'sponge',
      intensity: 'medium',
      description: 'Tap a sheer base through the center of the face, keeping the edge thin.',
      dependency: 'natural-01-skin-prep',
      product: {
        category: 'skin tint',
        shade: 'skin match',
        finish: 'natural',
      },
      placement: {
        area: 'center of face',
        anchor: 'around nose and cheeks',
        coverage: 'medium',
      },
      technique: {
        blendMode: 'diffused',
        strokeDirection: 'center_out',
        layerOrder: 'base',
        repeat: 2,
      },
      durationMs: 2600,
    },
    {
      id: 'natural-03-soft-brow',
      region: 'eyebrow',
      action: 'define',
      tool: 'brush',
      intensity: 'low',
      description: 'Brush brows upward and softly define sparse areas without a hard outline.',
      dependency: 'natural-02-even-base',
      product: {
        category: 'brow gel',
        shade: 'soft brown',
        finish: 'natural',
      },
      placement: {
        area: 'brow body and tail',
        coverage: 'small',
      },
      technique: {
        blendMode: 'precise',
        strokeDirection: 'follow_growth',
        layerOrder: 'definition',
        repeat: 1,
      },
      durationMs: 1800,
    },
    {
      id: 'natural-04-eye-open',
      region: 'eye',
      action: 'blend',
      tool: 'brush',
      intensity: 'low',
      description: 'Blend a neutral shade slightly upward at the outer third to open the eye.',
      dependency: 'natural-03-soft-brow',
      product: {
        category: 'eyeshadow',
        shade: 'taupe beige',
        finish: 'matte',
      },
      placement: {
        area: 'outer third of upper lid',
        anchor: 'outer corner',
        coverage: 'small',
      },
      technique: {
        blendMode: 'gradient',
        strokeDirection: 'upward',
        layerOrder: 'color',
        repeat: 2,
      },
      durationMs: 2400,
    },
    {
      id: 'natural-05-soft-lip',
      region: 'lip',
      action: 'apply',
      tool: 'finger',
      intensity: 'low',
      description: 'Press a muted rose tint into the center of the lips and soften outward.',
      dependency: 'natural-04-eye-open',
      product: {
        category: 'lip tint',
        shade: 'muted rose',
        finish: 'satin',
      },
      placement: {
        area: 'lip center',
        coverage: 'medium',
      },
      technique: {
        blendMode: 'soft',
        strokeDirection: 'lip_center_out',
        layerOrder: 'color',
        repeat: 1,
      },
      durationMs: 1800,
    },
    {
      id: 'natural-06-set-glow',
      region: 'face',
      action: 'set',
      tool: 'brush',
      intensity: 'low',
      description: 'Set only the T-zone so the cheeks keep a natural skin-like glow.',
      dependency: 'natural-05-soft-lip',
      product: {
        category: 'setting powder',
        finish: 'soft natural',
      },
      placement: {
        area: 'T-zone',
        anchor: 'forehead, nose, and chin',
        coverage: 'medium',
      },
      technique: {
        blendMode: 'diffused',
        strokeDirection: 'center_out',
        layerOrder: 'finish',
        repeat: 1,
      },
      durationMs: 1600,
    },
  ],
};
