import type { MakeupLook } from '../schema/makeup.schema';

export const westernGlam: MakeupLook = {
  id: 'look-western-glam-v01',
  name: 'Western Glam',
  goals: ['sculpted_face', 'slim_face', 'enlarge_eye', 'fuller_lip'],
  metadata: {
    style: 'western',
    version: '0.1',
    author: 'Makeup Engine',
    notes: 'A higher-contrast look with sculpted face structure, defined eyes, and fuller lips.',
  },
  steps: [
    {
      id: 'glam-01-full-base',
      region: 'face',
      action: 'apply',
      tool: 'sponge',
      intensity: 'high',
      description: 'Apply a polished full base while keeping the surface smooth and even.',
      product: {
        category: 'foundation',
        shade: 'skin match',
        finish: 'soft matte',
      },
      placement: {
        area: 'entire face',
        coverage: 'full',
      },
      technique: {
        blendMode: 'diffused',
        strokeDirection: 'center_out',
        layerOrder: 'base',
        repeat: 2,
      },
      durationMs: 3000,
    },
    {
      id: 'glam-02-sculpt',
      region: 'face',
      action: 'define',
      tool: 'brush',
      intensity: 'high',
      description: 'Define cheekbones and jawline with a controlled contour placement.',
      dependency: 'glam-01-full-base',
      product: {
        category: 'contour',
        shade: 'neutral brown',
        finish: 'matte',
      },
      placement: {
        area: 'cheek hollows and jawline',
        anchor: 'under cheekbone',
        coverage: 'medium',
      },
      technique: {
        blendMode: 'gradient',
        strokeDirection: 'upward',
        layerOrder: 'structure',
        repeat: 2,
      },
      durationMs: 2800,
    },
    {
      id: 'glam-03-arched-brow',
      region: 'eyebrow',
      action: 'define',
      tool: 'brush',
      intensity: 'high',
      description: 'Build a lifted brow arch with a clean tail and softer brow front.',
      dependency: 'glam-02-sculpt',
      product: {
        category: 'brow pomade',
        shade: 'deep brown',
        finish: 'matte',
      },
      placement: {
        area: 'brow arch and tail',
        coverage: 'small',
      },
      technique: {
        blendMode: 'precise',
        strokeDirection: 'follow_growth',
        layerOrder: 'definition',
        repeat: 1,
      },
      durationMs: 2200,
    },
    {
      id: 'glam-04-smoky-eye',
      region: 'eye',
      action: 'blend',
      tool: 'brush',
      intensity: 'high',
      description: 'Blend deeper shadow through the outer corner and crease for smoky dimension.',
      dependency: 'glam-03-arched-brow',
      product: {
        category: 'eyeshadow',
        shade: 'deep bronze',
        finish: 'satin',
      },
      placement: {
        area: 'outer lid and crease',
        anchor: 'outer V',
        coverage: 'medium',
      },
      technique: {
        blendMode: 'gradient',
        strokeDirection: 'outward',
        layerOrder: 'color',
        repeat: 3,
      },
      durationMs: 3200,
    },
    {
      id: 'glam-05-wing',
      region: 'eye',
      action: 'line',
      tool: 'brush',
      intensity: 'high',
      description: 'Create a lifted wing to elongate the eye and sharpen the lash line.',
      dependency: 'glam-04-smoky-eye',
      product: {
        category: 'gel liner',
        shade: 'black brown',
        finish: 'matte',
      },
      placement: {
        area: 'upper lash line',
        anchor: 'outer corner',
        coverage: 'small',
      },
      technique: {
        blendMode: 'precise',
        strokeDirection: 'upward',
        layerOrder: 'definition',
        repeat: 1,
      },
      durationMs: 2200,
    },
    {
      id: 'glam-06-full-lip',
      region: 'lip',
      action: 'define',
      tool: 'brush',
      intensity: 'high',
      description: 'Define the lip border and fill inward for a fuller balanced shape.',
      dependency: 'glam-05-wing',
      product: {
        category: 'lip liner',
        shade: 'rose brown',
        finish: 'matte',
      },
      placement: {
        area: 'lip border and center',
        coverage: 'medium',
      },
      technique: {
        blendMode: 'precise',
        strokeDirection: 'lip_center_out',
        layerOrder: 'definition',
        repeat: 2,
      },
      durationMs: 2400,
    },
  ],
};
